force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <label>Product Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/AddedDate__c.field-meta.xml
<CustomField>
    <fullName>AddedDate__c</fullName>
    <description>Дата добавления продукта</description>
    <label>AddedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Описание продукта</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ProductTriggerHelper.cls
public with sharing class ProductTriggerHelper {
    public static void processInsert(List<Product__c> products) {
        for(Product__c product : products){
            if(product.AddedDate__c == null){
                product.AddedDate__c = System.now();
            }
            formatDescription(product);
        }
    }

    public static void processUpdate(List<Product__c> products){
        for(Product__c product : products){
            formatDescription(product);
        }
    }

    private static void formatDescription(Product__c product){
        String description = product.Description__c;
        if(String.isNotBlank(description)){
            product.Description__c = description.normalizeSpace().abbreviate(200);
        }
    }
}