force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <label>Product Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/AddedDate__c.field-meta.xml
<CustomField>
    <fullName>AddedDate__c</fullName>
    <description>Дата добавления продукта</description>
    <label>AddedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Описание продукта</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/ImageURL__c.field-meta.xml
<CustomField>
    <fullName>ImageURL__c</fullName>
    <description>URL изображение продукта</description>
    <label>ImageURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>Цена продукта</description>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/UnitsAvailable__c.field-meta.xml
<CustomField>
    <fullName>UnitsAvailable__c</fullName>
    <description>Количество доступных единиц</description>
    <label>UnitsAvailable</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductTableController.cls
public with sharing class ProductTableController {
    @AuraEnabled
    public static List<Product__c> getProducts() {
        return [SELECT Id, Name, ImageURL__c, Description__c, UnitPrice__c, UnitsAvailable__c
            FROM Product__c
            ORDER BY AddedDate__c DESC
        ];
    }

    @AuraEnabled
    public static List<Product__c> createProduct(Product__c newProduct) {
        if (newProduct == null || String.isBlank(newProduct.Name) || newProduct.UnitPrice__c == null || newProduct.UnitPrice__c <= 0) {
            throw new AuraHandledException('Invalid product data: ' + newProduct);
        }
        insert newProduct;
        return getProducts();
    }
}